# -*- mode: ruby -*-
# vi: set ft=ruby :

$bootstrap = <<SCRIPT
yum install -y yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io -y
systemctl enable docker
systemctl start docker
curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

    config.vm.define "monitoring" do |monitoring|
      monitoring.vm.network "forwarded_port", guest: 3000, host: 3100
      monitoring.vm.network "forwarded_port", guest: 9090, host: 9190
      monitoring.vm.network "private_network", ip: "192.168.50.10"
      monitoring.vm.hostname = "monitoring"
      monitoring.vm.provision "file", source: "./dockprom", destination: "dockprom"
      monitoring.vm.provision "shell", inline: $bootstrap
      monitoring.vm.provision "shell", inline: <<-SHELL
      cd dockprom/
      docker-compose up -d
      docker-compose ps
      SHELL
    end

end
