---

- name: Ensure nginx is installed.
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Ensure PIP package-manager is installed.
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: install latest pyOpenSSL module if needed
  pip:
    name: pyOpenSSL
    state: latest
