---

- import_tasks: install.yml
  become: true

- import_tasks: configure.yml
  become: true

- name: Ensure nginx is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: nginx
    enabled: true
    state: started
