---

  - hosts: all

    tasks:

      - name: Install latest docker module on host
        pip:
          name: docker
          state: latest

      - name: Deploy Nginx Exporter
        docker_container:
          name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.10.0
          command:
            - -nginx.scrape-uri=https://192.168.10.7/nginx_status
            - -nginx.ssl-verify=false
            - -nginx.retries=10 
            - -web.telemetry-path=/metrics
          privileged: yes
          detach: yes
          restart_policy: always
          published_ports:
            - "9113:9113"

      - name: Copy files for custom exporter
        copy:
          src: ./custom_exporter
          dest: ~/

      - name: Build image for custom exporter
        docker_image:
          name: prometheus-custom-collector:latest
          source: build
          build:
            path: ~/custom_exporter
            http_timeout: 600

      - name: Deploy Custom Collector
        docker_container:
          name: custom-collector
          image: prometheus-custom-collector:latest
          privileged: yes
          detach: yes
          restart_policy: always
          published_ports:
            - "8000:8000"

      - name: Deploy Alertmanager-bot
        docker_container:
          name: alertmanager-bot
          privileged: yes
          detach: yes
          restart_policy: always
          image: metalmatze/alertmanager-bot:0.4.3
          env:
            TELEGRAM_ADMIN: "123456789"
            TELEGRAM_TOKEN: "XXXXXXX"
          command:
            - --alertmanager.url=http://192.168.10.6:9093
            - --log.level=info
            - --store=bolt
            - --bolt.path=/data/bot.db
          volumes:
            - ./data:/data
          published_ports:
            - "8080:8080"
