scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
rule_files:
    - './con.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
