# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    config.vm.define "zabbix-server" do |zabbix|
      zabbix.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      zabbix.vm.network "forwarded_port", guest: 80, host: 8080
      zabbix.vm.hostname = "zabbix"
      zabbix.vm.provision "file", source: "./ssl_check.conf", destination: "$HOME/ssl_check.conf"
      zabbix.vm.provision "file", source: "./ssl_check.sh", destination: "$HOME/ssl_check.sh"
      zabbix.vm.provision "shell", inline: <<-SHELL
        wget https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
        dpkg -i zabbix-release_5.4-1+ubuntu20.04_all.deb
        apt update
        apt install zabbix-server-pgsql zabbix-frontend-php php7.4-pgsql zabbix-nginx-conf zabbix-sql-scripts zabbix-agent postgresql postgresql-contrib -y
        sudo -u postgres psql -c "CREATE USER zabbix WITH PASSWORD 'zabbix';"
        sudo -u postgres psql -c "CREATE DATABASE zabbix OWNER zabbix;"
        zcat /usr/share/doc/zabbix-sql-scripts/postgresql/create.sql.gz | sudo -u zabbix psql zabbix
        sed -i 's!include /etc/nginx/sites-enabled/!#include /etc/nginx/sites-enabled/!g' /etc/nginx/nginx.conf
        sed -i 's!# DBPassword=!DBPassword=zabbix!g' /etc/zabbix/zabbix_server.conf
        systemctl restart zabbix-server zabbix-agent nginx php7.4-fpm
        systemctl enable zabbix-server zabbix-agent nginx php7.4-fpm
        cp -r ssl_check.* /etc/zabbix/zabbix_agentd.d/
        chmod +x /etc/zabbix/zabbix_agentd.d/ssl_check.sh
        systemctl restart zabbix-agent
      SHELL
    end

end
