---

- name: create alertmanager system group
  group:
    name: alertmanager
    system: true
    state: present

- name: create alertmanager system user
  user:
    name: alertmanager
    system: true
    shell: "/usr/sbin/nologin"
    group: alertmanager
    createhome: false

- name: Creating alertmanager and amtool config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: alertmanager
    mode: 0770
  with_items:
    - "/etc/alertmanager"
    - "/etc/amtool"

- name: create alertmanager data directory
  file:
    path: "/data/alertmanager"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: 0755

- name: Extracting alertmanager compressed file
  unarchive:
    src: "alertmanager-0.24.0.linux-amd64.tar.gz"
    dest: "/tmp"

- name: Copying alertmanager binaries to /usr/local/sbin
  copy:
    src: "/tmp/alertmanager-0.24.0.linux-amd64/{{item}}"
    dest: "/usr/local/sbin/{{item}}"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  with_items:
    - alertmanager
    - amtool

- name: Creating alertmanager SystemD unit
  template: 
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: '0644'
  notify: restart alertmanager

- name: Copying alertmanager.yml file
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: root
    group: alertmanager
    mode: '0740'
  notify: reload alertmanager
