{
 "title": "PROD.REDIS - 1",
 "description": "A Redis Server Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Version",
   "type": "singlestat",
   "description": "Redis Version",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis Version" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Replication role",
   "type": "singlestat",
   "description": "Replica info",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis replication role" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "singlestat",
   "description": "Redis Used Memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Instantaneous OPS per sec",
   "type": "singlestat",
   "description": "Number of commands processed per second",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis instantaneous OpsPerSec" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Clients Connected",
   "type": "singlestat",
   "description": "Total Clients Connected",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis Clients" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "singlestat",
   "description": "Total Commands Processed",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis total commands processed" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis Up Time",
   "type": "singlestat",
   "description": "Redis Up Time",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System CPU",
   "type": "graph",
   "description": "System CPU consumed by the Redis server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used cpu sys" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "graph",
   "description": "User CPU consumed by the Redis server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used cpu user" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Connections Received",
   "type": "graph",
   "description": "Total number of connections accepted by the server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": {
      "filter": "Redis total connections received"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "graph",
   "description": "Total number of commands processed by the server",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis total commands processed" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Instantaneous OPS per sec",
   "type": "graph",
   "description": "Number of commands processed per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis instantaneous OpsPerSec" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Rejected Connections",
   "type": "graph",
   "description": "Number of connections rejected because of maxclients limit",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis rejected connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Inputs Read Bytes",
   "type": "graph",
   "description": "The total number of bytes read from the network",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis total net input bytes" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Outputs Write Bytes",
   "type": "graph",
   "description": "The total number of bytes written to the network",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis total net output bytes" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Total number of bytes allocated by Redis using its allocator",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Peak Memory",
   "type": "graph",
   "description": "Peak memory consumed by Redis (in bytes)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used memory peak" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LUA Memory",
   "type": "graph",
   "description": "Number of bytes used by the Lua engine",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used memory lua" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "graph",
   "description": "Number of bytes that Redis allocated as seen by the operating system (a.k.a resident set size). This is the number reported by tools such as top(1) and ps(1)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis monitoring" },
     "group": { "filter": "Stage circuit" },
     "host": { "filter": "Redis-m" },
     "item": { "filter": "Redis used memory rss" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}